import type { Project } from "./projects";

export const candidateXProject: Project = {
  id: "candidatex",
  slug: "candidatex",
  aliases: ["cci", "candidate-capability-intelligence"],
  index: "06",
  title: "CandidateX",
  shortTitle: "CandidateX",
  kicker: "Candidate capability intelligence",
  purpose: "A provenance-grounded hiring decision-support system that turns candidate-supplied evidence into role-specific capability estimates, contradiction diagnostics, and targeted interview probes.",
  status: "Research prototype · source + live",
  role: "Research engineer · full-stack / evaluation systems",
  contribution: "I designed and implemented the end-to-end CandidateX research and product prototype represented by the repository: candidate intake, evidence acquisition boundaries, static analyzers, Candidate Evidence Graph construction, scoring, diagnostics, interview probes, backend APIs, and recruiter-facing web workflow.",
  outcome: "A reproducible research prototype that helps interviewers inspect technical evidence without making autonomous hire or reject decisions.",
  evidenceScope: "The CandidateX repository documents a Next.js 15 frontend, FastAPI backend, PostgreSQL/Redis infrastructure, static multi-language analysis, a Candidate Evidence Graph, role-capability scoring, and research experiment tooling. The submitted paper reports a controlled synthetic benchmark of 28,800 candidate-role evaluations. The repository separately contains a 4,800-sample supplementary implementation ablation harness. Neither should be described as validated real-world hiring performance. A public CandidateX deployment is available at candidatex-smoky.vercel.app.",
  technologies: ["Python", "FastAPI", "Next.js", "PostgreSQL", "Redis", "Static analysis"],
  art: "/media/hero-studio.svg",
  period: "2026",
  links: {
    live: "https://candidatex-smoky.vercel.app",
    source: "https://github.com/yorayriniwnl/CandidateX",
  },
  availability: { live: "verified", source: "verified" },
  visibility: { featured: true, portfolio: true, resume: true },
  media: [],
  problem: "Hiring evidence is fragmented across resumes, repositories, deployments, schemas, coding profiles, and interviews. Collapsing those signals into an opaque score hides provenance, uncertainty, and contradictions.",
  whyItMatters: "Interviewers need to know what a candidate claims, what the supplied artifacts actually support, where evidence is missing, and which questions would reduce uncertainty before making a human hiring decision.",
  constraints: [
    "The system is employer decision support only; it does not autonomously hire or reject candidates.",
    "Analysis stays inside a closed-world manifest of candidate-supplied resources rather than unconstrained identity discovery.",
    "Candidate repositories are inspected statically; untrusted candidate code is not executed.",
    "Missing evidence is represented as unknown coverage rather than an arbitrary zero capability score.",
  ],
  workflow: "A CV, job description, and candidate-supplied links are normalized into a manifest; evidence is acquired under safety constraints, analyzed into a provenance-backed graph, scored against role requirements, checked for contradictions, and converted into an interviewer dossier with prioritized probes.",
  hardPart: "The central engineering problem is preserving provenance and uncertainty while still producing a result that is useful to an interviewer. CandidateX therefore separates observed capability from evidence coverage and keeps source lineage beside the resulting diagnostics.",
  decisions: [
    { title: "Keep the human in the hiring loop", body: "CandidateX produces evidence, uncertainty, contradictions, and interview probes rather than an autonomous employment decision." },
    { title: "Never execute candidate code", body: "Repository analysis uses deterministic static parsing and manifest inspection so untrusted submissions do not become an execution surface." },
    { title: "Separate capability from coverage", body: "Role Capability Index summarizes observed evidence while Evidence Coverage communicates how much of the role is actually supported by sufficient evidence." },
  ],
  architecture: [
    "Candidate + role intake",
    "Safe evidence acquisition",
    "Static analyzers",
    "Candidate Evidence Graph",
    "Capability / uncertainty engine",
    "Contradiction + probe generation",
    "Recruiter dossier",
  ],
  implementation: [
    "The backend is organized around FastAPI, SQLAlchemy, provenance-aware domain contracts, acquisition guards, analyzers, scoring, graph construction, and a staged analysis pipeline.",
    "Static analyzers cover multiple programming-language and infrastructure artifacts without running candidate repositories.",
    "The Next.js recruiter workspace surfaces candidate intake, directory views, dossiers, comparison workflows, evidence state, and export paths.",
    "Research tooling preserves the paper-reported benchmark separately from the repository supplementary implementation ablation so the two experimental designs cannot be accidentally conflated.",
  ],
  testing: [
    "The repository includes scoring, theorem, security, database, research, pipeline, and frontend verification surfaces plus a paper-alignment regression contract.",
    "The public deployment provides a recruiter-facing application entry point; backend/runtime claims remain bounded by the repository's documented infrastructure and test evidence.",
  ],
  results: [
    "The repository connects candidate-supplied artifacts to an inspectable evidence graph and role-specific evaluation workflow.",
    "Scoring, coverage, contradiction diagnostics, and interview-probe generation are represented as distinct outputs instead of one opaque ranking.",
    "The submitted paper reports 28,800 synthetic candidate-role evaluations across six roles; the repository also contains a separate 4,800-sample supplementary implementation ablation harness.",
  ],
  metrics: [
    { label: "Capability dimensions", value: "12", context: "Canonical technical dimensions documented by the CandidateX scoring framework" },
    { label: "Paper benchmark", value: "28,800", context: "Synthetic candidate-role evaluations reported in the submitted paper across 16 seeds and 6 target roles" },
    { label: "Supplementary ablation", value: "4,800", context: "Separate repository implementation diagnostic; not the paper headline benchmark" },
  ],
  limitations: [
    "The paper benchmark and repository ablation are synthetic research evidence and must not be described as real-world hiring validity.",
    "The public deployment may use controlled demonstration data when the live backend is unavailable; demo records are not real candidate analyses.",
    "The public deployment demonstrates the application surface; production-grade backend availability, data durability, and operational SLOs should not be inferred unless separately measured.",
    "Any use in hiring requires careful legal, fairness, privacy, accessibility, and human-review governance beyond the software prototype itself.",
  ],
  lessons: [
    "Evidence provenance is more useful than a confident-looking score with no traceable source.",
    "Coverage and uncertainty need their own first-class outputs in evaluation systems.",
    "Research provenance must distinguish paper-reported results from later implementation diagnostics.",
  ],
  nextIteration: "Validate the scoring and probe-generation behavior with carefully designed human-reviewed studies rather than simulated cohorts alone, then publish calibration, fairness, and operational measurements.",
  claimIds: ["candidatex-paper-benchmark", "candidatex-supplementary-ablation"],
  seo: {
    title: "CandidateX · Candidate Capability Intelligence Case Study",
    description: "CandidateX is a provenance-grounded hiring decision-support research prototype using static evidence analysis, Candidate Evidence Graphs, role capability scoring, contradiction diagnostics, and interview probes.",
  },
};
