import type { Project } from "./projects";

export const candidateXProject: Project = {
  id: "candidatex",
  slug: "candidatex",
  aliases: ["cci", "candidate-capability-intelligence"],
  index: "06",
  title: "CandidateX",
  shortTitle: "CandidateX",
  kicker: "Candidate capability intelligence",
  purpose: "A provenance-grounded hiring decision-support system that turns candidate-supplied evidence into role-specific capability estimates, contradiction diagnostics, and targeted interview probes.",
  status: "Research prototype · source verified",
  role: "Research engineer · full-stack / evaluation systems",
  contribution: "I designed and implemented the end-to-end CandidateX research and product prototype represented by the repository: candidate intake, evidence acquisition boundaries, static analyzers, Candidate Evidence Graph construction, scoring, diagnostics, interview probes, backend APIs, and recruiter-facing web workflow.",
  outcome: "A reproducible research prototype that helps interviewers inspect technical evidence without making autonomous hire or reject decisions.",
  evidenceScope: "Repository evidence at commit e68febbb documents a Next.js 15 frontend, FastAPI backend, PostgreSQL/Redis infrastructure, static multi-language analysis, a Candidate Evidence Graph, role-capability scoring, and research experiment tooling. The published experiment results are simulation-based research evidence rather than validated hiring outcomes, and a stable public CandidateX application hostname is not currently verified for this portfolio.",
  technologies: ["Python", "FastAPI", "Next.js", "PostgreSQL", "Redis", "Static analysis"],
  art: "/media/hero-studio.svg",
  period: "2026",
  links: { source: "https://github.com/yorayriniwnl/CandidateX" },
  availability: { live: "unavailable", source: "verified" },
  visibility: { featured: true, portfolio: true, resume: true },
  media: [],
  problem: "Hiring evidence is fragmented across resumes, repositories, deployments, schemas, coding profiles, and interviews. Collapsing those signals into an opaque score hides provenance, uncertainty, and contradictions.",
  whyItMatters: "Interviewers need to know what a candidate claims, what the supplied artifacts actually support, where evidence is missing, and which questions would reduce uncertainty before making a human hiring decision.",
  constraints: [
    "The system is employer decision support only; it does not autonomously hire or reject candidates.",
    "Analysis stays inside a closed-world manifest of candidate-supplied resources rather than unconstrained identity discovery.",
    "Candidate repositories are inspected statically; untrusted candidate code is not executed.",
    "Missing evidence is represented as unknown coverage rather than an arbitrary zero capability score.",
  ],
  workflow: "A CV, job description, and candidate-supplied links are normalized into a manifest; evidence is acquired under safety constraints, analyzed into a provenance-backed graph, scored against role requirements, checked for contradictions, and converted into an interviewer dossier with prioritized probes.",
  hardPart: "The central engineering problem is preserving provenance and uncertainty while still producing a result that is useful to an interviewer. CandidateX therefore separates observed capability from evidence coverage and keeps source lineage beside the resulting diagnostics.",
  decisions: [
    { title: "Keep the human in the hiring loop", body: "CandidateX produces evidence, uncertainty, contradictions, and interview probes rather than an autonomous employment decision." },
    { title: "Never execute candidate code", body: "Repository analysis uses deterministic static parsing and manifest inspection so untrusted submissions do not become an execution surface." },
    { title: "Separate capability from coverage", body: "Role Capability Index summarizes observed evidence while Evidence Coverage communicates how much of the role is actually supported by sufficient evidence." },
  ],
  architecture: [
    "Candidate + role intake",
    "Safe evidence acquisition",
    "Static analyzers",
    "Candidate Evidence Graph",
    "Capability / uncertainty engine",
    "Contradiction + probe generation",
    "Recruiter dossier",
  ],
  implementation: [
    "The backend is organized around FastAPI, SQLAlchemy, provenance-aware domain contracts, acquisition guards, analyzers, scoring, graph construction, and a staged analysis pipeline.",
    "Static analyzers cover multiple programming-language and infrastructure artifacts without running candidate repositories.",
    "The Next.js recruiter workspace surfaces candidate intake, directory views, dossiers, comparison workflows, evidence state, and export paths.",
    "Research tooling reproduces deterministic simulated cohorts and ablation-study artifacts for the associated conference-paper methodology.",
  ],
  testing: [
    "The repository README documents unit, golden, property, security, database, and theorem-audit test surfaces across the backend and research layers.",
    "A public hosted acceptance path and current release CI state should be re-verified before presenting CandidateX as production-ready software.",
  ],
  results: [
    "The repository connects candidate-supplied artifacts to an inspectable evidence graph and role-specific evaluation workflow.",
    "Scoring, coverage, contradiction diagnostics, and interview-probe generation are represented as distinct outputs instead of one opaque ranking.",
    "The research layer includes deterministic multi-seed simulation and ablation tooling intended to reproduce paper tables and comparisons.",
  ],
  metrics: [
    { label: "Canonical role dimensions", value: "12", context: "Capability dimensions documented by the CandidateX scoring framework" },
    { label: "Research cohort", value: "4,800", context: "README-documented deterministic simulated candidates across 16 seeds; not real hiring outcomes" },
  ],
  limitations: [
    "The published research cohort is simulated and must not be described as evidence of real-world hiring validity.",
    "A stable public CandidateX deployment hostname has not been independently verified for the portfolio, so the clean project page exposes source but not a live CTA.",
    "Any use in hiring requires careful legal, fairness, privacy, accessibility, and human-review governance beyond the software prototype itself.",
  ],
  lessons: [
    "Evidence provenance is more useful than a confident-looking score with no traceable source.",
    "Coverage and uncertainty need their own first-class outputs in evaluation systems.",
  ],
  nextIteration: "Verify a stable public deployment, then validate the scoring and probe-generation behavior with carefully designed human-reviewed studies rather than simulated cohorts alone.",
  claimIds: ["candidatex-research-cohort"],
  seo: {
    title: "CandidateX · Candidate Capability Intelligence Case Study",
    description: "CandidateX is a provenance-grounded hiring decision-support research prototype using static evidence analysis, Candidate Evidence Graphs, role capability scoring, contradiction diagnostics, and interview probes.",
  },
};
